package com.bgame.multiblockdesigner.export;

import com.bgame.multiblockdesigner.definition.BlockRole;
import com.bgame.multiblockdesigner.definition.MultiblockDefinition;
import com.bgame.multiblockdesigner.definition.RelativeBlock;
import com.google.common.base.CaseFormat;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.ForgeRegistries;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

public class JavaExporter {

    public static String export(MultiblockDefinition def) {
        PatternNormalizer.NormalizedPattern pattern = PatternNormalizer.normalize(def);

        StringBuilder sb = new StringBuilder();
        String machineId = toMachineId(def.displayName);

        sb.append("// Generated by GTCEu Multiblock Designer\n\n");
        sb.append("public static final MultiblockMachineDefinition ").append(machineId.toUpperCase()).append(" = REGISTRATE\n");
        sb.append("    .multiblock(\"").append(machineId).append("\", WorkableElectricMultiblockMachine::new)\n");
        sb.append("    .rotationState(RotationState.ALL)\n");
        sb.append("    .recipeTypes(PhoenixRecipeTypes.AETHERIAL_FABIRCATION_RECIPES) // TODO: Change recipe type\n");
        sb.append("    .appearanceBlock(").append(appearanceBlock(def)).append(")\n");
        sb.append("    .pattern(definition -> {\n");
        sb.append("        return FactoryBlockPattern.start()\n");

        // Aisles
        for (int y = 0; y < pattern.sizeY; y++) {
            sb.append("            .aisle(");
            for (int z = 0; z < pattern.sizeZ; z++) {
                sb.append("\"").append(pattern.aisles[y][z]).append("\"");
                if (z < pattern.sizeZ - 1) sb.append(", ");
            }
            sb.append(")\n");
        }

        // Where clauses
        sb.append("            .where(\"C\", Predicates.controller(Predicates.blocks(definition.get())))\n");

        for (Map.Entry<Character, List<RelativeBlock>> entry : pattern.keyMap.entrySet()) {
            char key = entry.getKey();
            if (key == 'C') continue;

            List<RelativeBlock> rbs = entry.getValue();
            if (rbs.isEmpty()) continue;

            RelativeBlock representative = rbs.get(0);
            ResourceLocation blockId = ForgeRegistries.BLOCKS.getKey(representative.state.getBlock());

            sb.append("            .where(\"").append(key).append("\", ");
            sb.append(whereClause(representative, blockId));
            sb.append(")\n");
        }

        if (hasAnySpace(pattern)) {
            sb.append("            .where(\" \", Predicates.any())\n");
        }

        sb.append("            .build();\n");
        sb.append("    })\n");
        sb.append("    .workableCasingModel(").append(casingModel(def)).append(",\n");
        sb.append("        GTCEu.id(\"block/multiblock/active_overlay\"))\n");
        sb.append("    .register();\n");

        return sb.toString();
    }

    private static String whereClause(RelativeBlock rb, ResourceLocation blockId) {
        StringBuilder sb = new StringBuilder();
        String blockRef = toJavaBlockRef(blockId);
        sb.append("Predicates.blocks(").append(blockRef).append(")");

        if (!rb.abilities.isEmpty()) {
            for (String ability : rb.abilities) {
                sb.append("\n                .or(Predicates.abilities(PartAbility.").append(ability).append("))");
            }
        }
        return sb.toString();
    }

    private static String appearanceBlock(MultiblockDefinition def) {
        return def.blocks.stream()
            .filter(b -> b.role == BlockRole.CASING)
            .findFirst()
            .map(b -> {
                ResourceLocation key = ForgeRegistries.BLOCKS.getKey(b.state.getBlock());
                return toJavaBlockRef(key);
            })
            .orElse("Blocks.IRON_BLOCK");
    }

    private static String casingModel(MultiblockDefinition def) {
         return def.blocks.stream()
            .filter(b -> b.role == BlockRole.CASING)
            .findFirst()
            .map(b -> {
                ResourceLocation key = ForgeRegistries.BLOCKS.getKey(b.state.getBlock());
                if (key == null) return "GTCEu.id(\"block/casings/solid/machine_casing_clean_stainless_steel\")";
                return "GTCEu.id(\"block/casings/solid/" + key.getPath() + "\")";
            })
            .orElse("GTCEu.id(\"block/casings/solid/machine_casing_clean_stainless_steel\")");
    }

    private static String toJavaBlockRef(ResourceLocation blockId) {
        if (blockId == null) return "Blocks.STONE";

        // Attempt to find the block via reflection in known classes
        String reflectiveRef = findBlockField(blockId);
        if (reflectiveRef != null) {
            return reflectiveRef;
        }

        // Fallback to heuristic if reflection fails
        if ("gtceu".equals(blockId.getNamespace())) {
            String fieldName = CaseFormat.LOWER_UNDERSCORE.to(CaseFormat.UPPER_UNDERSCORE, blockId.getPath())
                .replace("BLOCK", "")
                .replaceAll("_+", "_");
            // Default to GTCEuBlocks if we can't find it
            return "GTCEuBlocks." + fieldName + ".get()";
        } else {
            return "ForgeRegistries.BLOCKS.getValue(new ResourceLocation(\"" + blockId + "\"))";
        }
    }

    private static String findBlockField(ResourceLocation targetBlockId) {
        Block targetBlock = ForgeRegistries.BLOCKS.getValue(targetBlockId);
        if (targetBlock == null) return null;

        // List of classes known to hold block definitions
        String[] classNames = {
            "com.gregtechceu.gtceu.common.data.GTBlocks",
            "com.gregtechceu.gtceu.common.data.GTCEuBlocks"
        };

        for (String className : classNames) {
            try {
                Class<?> clazz = Class.forName(className);
                for (Field field : clazz.getFields()) {
                    if (!Modifier.isPublic(field.getModifiers()) || !Modifier.isStatic(field.getModifiers())) {
                        continue;
                    }

                    Object fieldValue = field.get(null);
                    if (fieldValue == null) continue;

                    Block blockInField = null;
                    // Handle direct Block fields, Suppliers, and BlockRegistryObjects
                    if (fieldValue instanceof Block) {
                        blockInField = (Block) fieldValue;
                    } else if (fieldValue instanceof Supplier) {
                        Object supplied = ((Supplier<?>) fieldValue).get();
                        if (supplied instanceof Block) {
                            blockInField = (Block) supplied;
                        }
                    }
                    // Using string for class name to avoid compile-time dependency if not present
                    else if (fieldValue.getClass().getName().endsWith("BlockRegistryObject")) {
                         try {
                            Method getMethod = fieldValue.getClass().getMethod("get");
                            Object gotValue = getMethod.invoke(fieldValue);
                            if (gotValue instanceof Block) {
                                blockInField = (Block) gotValue;
                            }
                        } catch (Exception e) { /* Ignore, can't get block */ }
                    }

                    if (targetBlock == blockInField) {
                        // Found it!
                        String fieldAccess = clazz.getSimpleName() + "." + field.getName();
                        if (fieldValue instanceof Supplier || fieldValue.getClass().getName().endsWith("BlockRegistryObject")) {
                            return fieldAccess + ".get()";
                        } else {
                            return fieldAccess; // It's a direct block field
                        }
                    }
                }
            } catch (Exception e) {
                // ClassNotFound, SecurityException, etc. Silently fail and move on.
            }
        }
        return null; // Not found
    }

    private static String toMachineId(String displayName) {
        return displayName.toLowerCase()
            .replaceAll("[^a-z0-9_]", "_")
            .replaceAll("_+", "_")
            .replaceAll("^_|_$", "");
    }

    private static boolean hasAnySpace(PatternNormalizer.NormalizedPattern pattern) {
        for (String[] aisle : pattern.aisles)
            for (String row : aisle)
                if (row.contains(" ")) return true;
        return false;
    }
}