package com.bgame.multiblockdesigner.export;

import com.bgame.multiblockdesigner.definition.BlockRole;
import com.bgame.multiblockdesigner.definition.MultiblockDefinition;
import com.bgame.multiblockdesigner.definition.RelativeBlock;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.List;
import java.util.Map;
import java.util.StringJoiner;

// Exports a {MultiblockDefinition} as a KubeJS GTCEu startup script.
public class KubeJSExporter {

    public static String export(MultiblockDefinition def) {
        PatternNormalizer.NormalizedPattern pattern = PatternNormalizer.normalize(def);

        StringBuilder sb = new StringBuilder();
        String machineName = toMachineName(def.displayName);

        sb.append("// Generated by GTCEu Multiblock Designer\n");
        sb.append("// Definition: ").append(def.displayName)
          .append(" | id: ").append(def.id)
          .append(" | ").append(def.blocks.size()).append(" blocks\n\n");

        sb.append("GTCEuStartupEvents.registry('gtceu:machine', event => {\n");
        sb.append("  event.create('").append(machineName).append("', 'multiblock')\n");
        sb.append("    .rotationState(RotationState.NON_Y_AXIS)\n");
        sb.append("    .recipeType('gtceu:recipe_type') // TODO: set your recipe type\n");
        sb.append("    .appearanceBlock(").append(appearanceBlock(def)).append(")\n");
        sb.append("    .pattern(definition => FactoryBlockPattern.start()\n");

        // Aisles — bottom to top (Y ascending)
        for (int y = 0; y < pattern.sizeY; y++) {
            String[] aisleRows = pattern.aisles[y];
            StringJoiner joiner = new StringJoiner(", ");
            for (String row : aisleRows) {
                joiner.add("'" + row + "'");
            }
            sb.append("      .aisle(").append(joiner.toString()).append(")\n");
        }

        // Where clauses
        sb.append("      .where('C', Predicates.controller(Predicates.blocks(definition.get())))\n");

        for (Map.Entry<Character, List<RelativeBlock>> entry : pattern.keyMap.entrySet()) {
            char key = entry.getKey();
            if (key == 'C') continue;

            List<RelativeBlock> rbs = entry.getValue();
            if (rbs.isEmpty()) continue;

            BlockRole role = pattern.keyRoles.get(key);
            RelativeBlock representative = rbs.get(0);
            ResourceLocation blockId = ForgeRegistries.BLOCKS.getKey(representative.state.getBlock());
            String blockRef = blockId != null ? blockId.toString() : "minecraft:stone";
            String blockClassName = representative.state.getBlock().getClass().getName();

            sb.append("      // ").append(key).append(" -> ").append(blockClassName).append("\n");
            sb.append("      .where('").append(key).append("', ");
            sb.append(whereClause(key, representative, blockRef));
            sb.append(")\n");
        }

        // Space = any
        boolean hasSpaces = hasAnySpace(pattern);
        if (hasSpaces) {
            sb.append("      .where(' ', Predicates.any())\n");
        }

        sb.append("      .build()\n");
        sb.append("    )\n");
        sb.append("    .workableCasingRenderer(\n");
        sb.append("      '").append(casingTexture(def)).append("',\n");
        sb.append("      GTCEu.id('block/multiblock/active_overlay') // set overlay\n");
        sb.append("    )\n");
        sb.append("})\n");

        return sb.toString();
    }

    // Where clause per role
    private static String whereClause(Character key, RelativeBlock rb, String blockId) {
        StringBuilder sb = new StringBuilder();
        sb.append("Predicates.blocks('").append(blockId).append("')");

        if (!rb.abilities.isEmpty()) {
            for (String ability : rb.abilities) {
                sb.append("\n        .or(Predicates.abilities(PartAbility.").append(ability).append("))");
            }
        }
        return sb.toString();
    }

    // Helpers
    private static String appearanceBlock(MultiblockDefinition def) {
        return def.blocks.stream()
            .filter(b -> b.role == BlockRole.CASING)
            .findFirst()
            .map(b -> {
                ResourceLocation key = ForgeRegistries.BLOCKS.getKey(b.state.getBlock());
                return key != null
                    ? "Block.getBlock('%s')".formatted(key)
                    : "Block.getBlock('minecraft:iron_block')";
            })
            .orElse("Block.getBlock('minecraft:iron_block')");
    }

    // Derives a GTCEu texture path from the casing block.
    private static String casingTexture(MultiblockDefinition def) {
        return def.blocks.stream()
            .filter(b -> b.role == BlockRole.CASING)
            .findFirst()
            .map(b -> {
                ResourceLocation key = ForgeRegistries.BLOCKS.getKey(b.state.getBlock());
                if (key == null) return "minecraft:block/iron_block";
                // If its a GTCEu block, use its texture path directly
                if ("gtceu".equals(key.getNamespace())) {
                    return "gtceu:block/casings/solid/" + key.getPath();
                }
                return key.getNamespace() + ":block/" + key.getPath();
            })
            .orElse("minecraft:block/iron_block");
    }

    private static String toMachineName(String displayName) {
        return displayName.toLowerCase()
            .replaceAll("[^a-z0-9_]", "_")
            .replaceAll("_+", "_")
            .replaceAll("^_|_$", "");
    }

    private static boolean hasAnySpace(PatternNormalizer.NormalizedPattern pattern) {
        for (String[] aisle : pattern.aisles)
            for (String row : aisle)
                if (row.contains(" ")) return true;
        return false;
    }
}